### ISSUE TITLE
Axiom WMS no longer at this location?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#28]
While preparing a demo for the DMAC meeting on TerriaJS using CSW to find ROMS model results:
![2017-03-10_8-05-48](https://cloud.githubusercontent.com/assets/1872600/23796414/cd40254e-0568-11e7-9134-ab18ed425c62.png)

I discovered that the WMS endpoint in the metadata:
http://pdx.axiomalaska.com/ncWMS/wms?service=WMS&version=1.3.0&request=GetCapabilities
gives a 502 Bad Gateway. 

@kwilcox, can you investigate?

**Comment by kwilcox** [comment]
Yup, fixing!

**Comment by kwilcox** [comment]
Its fixed in our THREDDS catalogs and the ISOs are being re-generated right now. I think the IOOS registry harvests every 24 hours and it last happened 17 hours ago... so this should be good by tomorrow morning.

**Comment by lukecampbell** [comment]
you can login to the registry and click reharvest to have the changes apply sooner, it only takes 30m (assuming light load) to sync it with CKAN.

**Comment by rsignell-usgs** [comment]
@lukecampbell , can I login to the registry and click reharvest?

Where are the registry instructions?
I'm guessing these are not them:
http://ioos.github.io/registry/ioos_registration_ngdc/

**Comment by lukecampbell** [comment]
https://ioos.github.io/catalog/pages/registry/

**Comment by rsignell-usgs** [comment]
@lukecampbell I tried to create a new account and it said I already had one.  
I then tried to send password and got internal error:
![2017-03-10_13-12-41](https://cloud.githubusercontent.com/assets/1872600/23807733/c33ad0ea-0594-11e7-845c-b54097fd1604.png)

**Comment by lukecampbell** [comment]
That's certainly a bug. The logs say the reason is because the email address is unverified but it should say that on the UI.

**Comment by lukecampbell** [comment]
@rsignell-usgs if you go to the "Register page" and click the link on the right, it should send another verification.

![screen_shot_2017-03-10_at_1_44_31_pm](https://cloud.githubusercontent.com/assets/1155163/23808434/dac1c432-0597-11e7-8031-7d85ca2e1cba.png)

**Comment by rsignell-usgs** [comment]
@lukecampbell , that's what throws the internal server error. 

I click that button, enter my email address, and then when I submit that I get the error. 

And I don't get an e-mail.

**Comment by lukecampbell** [comment]
that's even worse. Thanks for reporting it, I'm going to delete your account and you should be able to register for a new one again.

**Comment by lukecampbell** [comment]
K, the account is deleted, could you try again please?

**Comment by rsignell-usgs** [comment]
done

**Comment by rsignell-usgs** [comment]
When I try to login, it says "check your email for your confirmation email"
But I don't have any confirmation email.   I checked spam, etc.

  I just have the initial "welcome aboard" email.

**Comment by lukecampbell** [comment]
I just created a new account for myself and I got the verification email. 

> To verify your email address (REDACTED) visit the following link:
> 
> https://registry.ioos.us/users/verify/REDACTED
> 
> If you did not request this verification, please ignore this email. If you feel something is wrong, please contact our support team: admin@ioos.us.

**Comment by rsignell-usgs** [comment]
argh.  I see the email now.  I got it 3 minutes *before* the Welcome email.   But because I got 3 other mail messages in between, I didn't even see it.  I was expecting it *after* the Welcome email.

**Comment by lukecampbell** [comment]
ok cool, I was starting to dig into how/why one email could get through but another one didn't. I was starting to imagine some incredibly complex sophisticated government spam filtering.

**Comment by rsignell-usgs** [comment]
So now that I'm in at
https://registry.ioos.us/harvests
how do I figure out what to reharvest and how do I do it?

I tried the Unidata WAF listed as
http://thredds.axiomdatascience.com/iso/unidata/
but that gave a 404

**Comment by lukecampbell** [comment]
So now that we got the registration process sorted. @kwilcox will need to agree to let me give you administrative access for Unidata and/or AOOS wherever the harvest is for.

**Comment by lukecampbell** [comment]
Only members belonging to an organization can manipulate or change that organization's harvests.

**Comment by rsignell-usgs** [comment]
I guess I don't really need admin as long as @kwilcox can do it.   He should do it anyway since the Unidata WAF probably moved somewhere else also.

**Comment by kwilcox** [comment]
I hearby give @rsignell-usgs the ability to reharvest the Unidata data source (which I just fixed: http://thredds.axiomdatascience.com/iso/unidata/)

**Comment by lukecampbell** [comment]
K, @rsignell-usgs you are part of the Unidata group and can reharvest Unidata harvests.

**Comment by rsignell-usgs** [comment]
I just tried reharvesting the Unidata WAF and it worked!

@kwilcox , to address the original issue with CENCOOS ROMS raised here,  you just need to reharvest the CENCOOS WAF?

**Comment by lukecampbell** [comment]
Is this all set?

**Comment by rsignell-usgs** [comment]
Yes, it's all set.   I can see the correct WMS endpoint now.    I still can't access the Axiom ncWMS endpoint with TerriaJS because the getCaps is 360Mb, but that's another issue.

**Comment by lukecampbell** [comment]
360 MiB!?

**Comment by rsignell-usgs** [comment]
The getcaps is all timestamps of mostly regularly spaced data.    According to @kwilcox, it's an old, but highly-customized version of ncWMS that is great for speedily responding to large numbers of requests, but doesn't allow for the setting `<intervalTime>true</intervalTime>` that was added later.
